/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pi2semestre;

import com.mycompany.pi2semestre.models.Produto;
import com.mycompany.pi2semestre.models.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author DomiU
 */
public class JPanelInformacoes extends javax.swing.JPanel {
    
    private Produto produto;
    private Usuario usuario;

    /**
     * Creates new form JPanelProduto
     */
    public JPanelInformacoes(Produto produto) {
        initComponents();
         jLabelNome.setText(produto.getNome());
        jLabelPreco.setText("R$ " + produto.getPreco());
        jLabelVendidos.setText(produto.getQuantidadeEmEstoque()+ " disponíveis");
        jLabelDescricao.setText(produto.getDescricao());
        this.produto = produto;
              //  jLabelImagem.setIcon(new ImageIcon(produto.getImagem().getScaledInstance(222, 146, Image.SCALE_SMOOTH)));
                
              
                         
        jLabelImagem.setBackground(Color.blue);
    }
    
    
   

    public JPanelInformacoes(Usuario usuario) {
        initComponents();
        jLabelNome.setText(usuario.getNome());
        jLabelPreco.setText(usuario.getCpf() +"");
        jLabelVendidos.setText(usuario.getComprasRealizadas() + " compras");
        jLabelDescricao.setText(usuario.getEmail());
        this.usuario = usuario;
    
    }
    
    
    

  

    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
          g.setColor(Color.BLACK);
        g.drawLine(0,217,this.getWidth(),217);
    }
    
    
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnProduto = new javax.swing.JPopupMenu();
        itemInformacoes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemCarrinho = new javax.swing.JMenuItem();
        itemPrincipais = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemEditar = new javax.swing.JMenuItem();
        itemExcluir = new javax.swing.JMenuItem();
        jLabelImagem = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelVendidos = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();

        itemInformacoes.setText("Exibir informações");
        itemInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacoesActionPerformed(evt);
            }
        });
        mnProduto.add(itemInformacoes);
        mnProduto.add(jSeparator1);

        itemCarrinho.setText("Adicionar ao carrinho");
        mnProduto.add(itemCarrinho);

        itemPrincipais.setText("Em destaque");
        mnProduto.add(itemPrincipais);
        mnProduto.add(jSeparator2);

        itemEditar.setText("Alterar");
        itemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarActionPerformed(evt);
            }
        });
        mnProduto.add(itemEditar);

        itemExcluir.setText("Excluir");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        mnProduto.add(itemExcluir);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(224, 293));
        setMinimumSize(new java.awt.Dimension(224, 293));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jLabelImagem.setBackground(new java.awt.Color(255, 153, 51));
        jLabelImagem.setOpaque(true);

        jLabelNome.setBackground(new java.awt.Color(0, 153, 204));
        jLabelNome.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabelNome.setText("Nome produto");

        jLabelVendidos.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jLabelVendidos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelVendidos.setText("1000 vendidos");
        jLabelVendidos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabelPreco.setFont(new java.awt.Font("Segoe UI Emoji", 1, 13)); // NOI18N
        jLabelPreco.setText("R$ 6456");

        jLabelDescricao.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabelDescricao.setText("DESCRICAO DESCRICAO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jLabelVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPreco)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescricao)
                .addGap(0, 52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        System.out.println("363hfghfhfghfghhghfhhghhghfghfghh");
       if (evt.isPopupTrigger()){
            mnProduto.show(this, evt.getX(), evt.getY());
            
        }
    }//GEN-LAST:event_formMouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println(" --------- INFORMAÇÕES DO PRODUTO: ");
        System.out.println(produto.toString());
    }//GEN-LAST:event_formMouseClicked

    private void itemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarActionPerformed
        
        if (usuario != null) {
            CadastroCliente cadastroCliente = new CadastroCliente(usuario);
            cadastroCliente.setVisible(true);
        } else {
            CadastroProduto cadastroProduto = new CadastroProduto(produto);
            cadastroProduto.setVisible(true);
        }
        
    }//GEN-LAST:event_itemEditarActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        
        if (usuario != null) 
            usuario.desativar();
         else
            produto.desativar();
        
        JPanelListagemProduto.jPanelListagemProduto.revalidate();
    }//GEN-LAST:event_itemExcluirActionPerformed

    private void itemInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacoesActionPerformed
         
        JFrameExibirUsuario jFrameExibirUsuario;
        
       if(usuario != null) {
                       jFrameExibirUsuario = new JFrameExibirUsuario(usuario);
        
        jFrameExibirUsuario.setVisible(true);
       }

    }//GEN-LAST:event_itemInformacoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCarrinho;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemInformacoes;
    private javax.swing.JCheckBoxMenuItem itemPrincipais;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelVendidos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu mnProduto;
    // End of variables declaration//GEN-END:variables

    
}
