/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pi2semestre;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author DomiU
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnAnunciar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Anunciar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _add square_.png"))); // NOI18N
        jButton5.setText("Anunciar");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _shopping cart_.png"))); // NOI18N
        jButton7.setText("Anunciar");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _category_.png"))); // NOI18N
        jButton11.setText("Anunciar");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setBackground(new java.awt.Color(0, 0, 0));

        btnAnunciar.setBackground(new java.awt.Color(0, 0, 0));
        btnAnunciar.setForeground(new java.awt.Color(255, 255, 255));
        btnAnunciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _add square_.png"))); // NOI18N
        btnAnunciar.setText("Anunciar");
        btnAnunciar.setBorder(null);
        btnAnunciar.setBorderPainted(false);
        btnAnunciar.setContentAreaFilled(false);
        btnAnunciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnunciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnunciarActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _menu_.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnCarrinho.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _shopping cart_.png"))); // NOI18N
        btnCarrinho.setText("Carrinho");
        btnCarrinho.setBorder(null);
        btnCarrinho.setBorderPainted(false);
        btnCarrinho.setContentAreaFilled(false);
        btnCarrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarrinho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _profile circle_.png"))); // NOI18N
        btnPerfil.setText("Cadastro");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnCategorias.setBackground(new java.awt.Color(0, 0, 0));
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _category_.png"))); // NOI18N
        btnCategorias.setText("Categorias");
        btnCategorias.setBorder(null);
        btnCategorias.setBorderPainted(false);
        btnCategorias.setContentAreaFilled(false);
        btnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSaldo.setBackground(new java.awt.Color(0, 0, 0));
        btnSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon _wallet money_.png"))); // NOI18N
        btnSaldo.setText("Saldo");
        btnSaldo.setBorder(null);
        btnSaldo.setBorderPainted(false);
        btnSaldo.setContentAreaFilled(false);
        btnSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaldo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnSaldo)
                .addGap(215, 215, 215)
                .addComponent(btnCategorias)
                .addGap(93, 93, 93)
                .addComponent(btnAnunciar)
                .addGap(87, 87, 87)
                .addComponent(btnCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(btnPerfil)
                .addGap(43, 43, 43)
                .addComponent(btnMenu)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnMenu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSaldo)
                        .addComponent(btnAnunciar)
                        .addComponent(btnCarrinho)
                        .addComponent(btnCategorias)
                        .addComponent(btnPerfil)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnAnunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnunciarActionPerformed
        CadastroProduto cadastroProduto = new CadastroProduto();
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_btnAnunciarActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.setColor(Color.WHITE);
        g.drawLine(0, this.getHeight()-1, this.getWidth(), this.getHeight()-1);
    }

            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnunciar;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
